server:
  port: 8888
#1.改变默认的静态资源路径
#访问的路径是当前的项目+res+静态资源名=静态资源文件下找
#http://localhost:8888/res/s:png
spring:
  resources:
    static-locations: [classpath:/static/]
    add-mappings: true
    cache:
      period: 11000
  mvc:
    hiddenmethod:
      filter:
        enabled: true #开启页面表单的Rest功能

  #    2.给静态资源添加前缀为res
#    前缀会导致 welcome.page功能失效也会导致Favicon功能失效
#    static-path-pattern: /res/**
    # 3. 修改默认的静态资源路径，即其他的默认的位置会失效
#  resources:
#    设置静态资源路径为类路径下的 haha文件夹/和static文件夹下
#    多个静态资源路径之间使用 逗号 隔开
#    可以使用数组，各个路径之间使用，隔开
#    访问路径：http://localhost:8888/res/mr.png:
#    static-locations: [classpath:/haha/,/stiatic/]

#4.开启Rest风格的hiddenmethod的拦Filter截器，默认为false,
#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

